POST http://localhost:8080/events
content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzQ2NDgzMTA0LCJ1c2VySWQiOjN9.GNS6OvDfZBtEmQuH2Hd9NTWz5rS7hT7f2wsaoZpxtkQ

{
    "name":"new event",
    "description":"new event",
    "location":"new event",
    "datetime":"2020-10-10T15:00:00.000Z"
}

# POST http://localhost:8080/events
# Content-Type: application/json

# {
#     "name": "abc",
#     "description": "demo",
#     "location": "demo",
#     "datetime": "2020-10-10T15:00:00.000Z"
# }