POST http://localhost:8080/events
content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzQ2NjIwNDY2LCJ1c2VySWQiOjN9.3s8vXN3Lg6DQUZ0j3oI4VDl1E-F1lMijhNLyEGfwpxs

{
    "name":"new event",
    "description":"new event",
    "location":"new event",
    "datetime":"2020-10-10T15:00:00.000Z"
}

# POST http://localhost:8080/events
# Content-Type: application/json

# {
#     "name": "abc",
#     "description": "demo",
#     "location": "demo",
#     "datetime": "2020-10-10T15:00:00.000Z"
# }