POST http://localhost:8080/events
content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzQ2NjkzNzU5LCJ1c2VySWQiOjF9.3s806ZO5LI8LiOhf0fYbq39XP5z1C0nmpXf_3be9Azg

{
    "name":"new 2 event",
    "description":"new event",
    "location":"new event",
    "datetime":"2020-10-10T15:00:00.000Z"
}

# POST http://localhost:8080/events
# Content-Type: application/json

# {
#     "name": "abc",
#     "description": "demo",
#     "location": "demo",
#     "datetime": "2020-10-10T15:00:00.000Z"
# }