DELETE http://localhost:8080/events/2/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiZXhwIjoxNzQ2Njk4NjE4LCJ1c2VySWQiOjF9.-4kRbDfnpWqDcL8Bz3Nbx_9cCO_X1-8SkmzzIDNP8wU